application:
  time_zone: "${APPLICATION_TIME_ZONE: Asia/Shanghai}"
  version: "${ROSEN_VERSION: 1.0.1}"
theme:
  path: "${THEME_PATH: ./themes}"
  default: "${DEFAULT_THEME: haku}"
database:
  type: "${DATABASE_TYPE: postgres}"
  host: "${DATABASE_HOST: 127.0.0.1}"
  port: ${DATABASE_PORT:5432}
  username: "${DATABASE_USERNAME: root}"
  password: "${DATABASE_PASSWORD: 123456}"
  database: "${DATABASE_DB: upay}"
  parse_time: true
  time_zone: Asia%2FShanghai # Asia/Shanghai
  pool:
    max_conn: ${DATABASE_MAX_CONN:10} # 10 connections
    max_idle_conn: ${DATABASE_MAX_IDLE_CONN:5} # 5 connections
    max_idle_time: ${DATABASE_MAX_IDLE_TIME:5} # 5 minutes
    max_life: ${DATABASE_CONN_MAX_LIFETIME:28800} # 8 hours
server:
  port: ${SERVER_PORT:3000}
  ip: "${SERVER_IP: 0.0.0.0}"
  mode: "${SERVER_MODE: debug}" # check gin mode (debug | release | test)
logger:
  level: "${LOGGER_LEVEL: info}"
  encoding: "${LOGGER_ENCODING: console}"
  colors: ${LOGGER_COLORS:true}
  time_format: "${LOGGER_TIME_FORMAT: 2006-01-02 15:04:05.000}"